version: '0.2'

phases:
  build:
    commands:
      - docker-compose up -d
      - docker-compose run app pipenv --three
      - docker-compose run app pipenv install
      - docker-compose run app pipenv install --dev
      - docker-compose run app pipenv run pytest --junitxml='pytest-log.xml'

reports:
  pytest_reports:
    files:
      - 'pytest-log.xml'
    base-directory: '.'
    file-format: JUNITXML
