AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild role

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: user-codebuild-base-role
      Description: 'CodeBuild base role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: codebuild.amazonaws.com

  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: user-codebuild-base-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketAcl'
              - 's3:GetBucketLocation'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'codebuild:CreateReportGroup'
              - 'codebuild:CreateReport'
              - 'codebuild:UpdateReport'
              - 'codebuild:BatchPutTestCases'
              - 'codebuild:BatchPutCodeCoverages'
            Resource: '*'
      Roles:
        - !Ref CodeBuildRole

Outputs:
  CodeBuildRoleArn:
    Description: CodeBuild role arn
    Value: !GetAtt CodeBuildRole.Arn
    Export:
      Name: role-arn-codebuild-base
