AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild template include GitHub Webhook event and notify build status to SNS

Parameters:
  ProjectName:
    Type: String
    Description: The name of the build project. The name must be unique across all of the projects in your AWS account.

  GitHubRepository:
    Type: String
    Description: The HTTPS clone URL to the repository that contains the source and the buildspec file. You must connect your AWS account to your GitHub account.

  StartBuildPattern:
    Type: String
    Description: A webhook event triggers a build when the base reference matches the regular expression pattern (for example, refs/heads/branch-name)

  EmailAddress:
    Type: String
    Description: The email address to notify build status.

Resources:
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: !Ref StartBuildPattern
      ServiceRole: user-codebuild-base-role
      Source:
        Auth:
          Type: OAUTH
        Location: !Ref GitHubRepository
        Type: GITHUB
        ReportBuildStatus: true

  # ロググループの作成
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${ProjectName}
      RetentionInDays: 7

  # CodeBuildからの通知を受け取るSNSの定義
  CodeBuildSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: codebuild-notification
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email

  # CodeBuildに対するSNSTopicへのアクセスポリシーを付与
  CodeBuildSNSPermission:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'SNS:Publish'
            Principal:
              Service: 'codestar-notifications.amazonaws.com'
            Resource: !Sub 'arn:aws:sns:ap-northeast-1:${AWS::AccountId}:codebuild-notifications'
      Topics:
        - !Ref CodeBuildSNSTopic

  # SNSへの結果通知リソース
  CodeStarNotification:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: 'Notify Build Status to SNS'
      DetailType: FULL
      Resource: !GetAtt CodeBuild.Arn
      EventTypeIds:
        - 'codebuild-project-build-state-failed'
        - 'codebuild-project-build-state-succeeded'
        - 'codebuild-project-build-state-in-progress'
        - 'codebuild-project-build-state-stopped'
      Targets:
        - TargetType: SNS
          TargetAddress: !Ref CodeBuildSNSTopic
